print("hello world")
age = 25
print("I am",age,"years old")
print(type("Charizard"))
print(type(256))
print(type(3.141592))
print("It's about time!")
print('Tell me, "how is it going?"')
print('''tell me, "How's it going?" ''')
int(86.5)
str(86.5)
float(532)
len("Thumper")
int("87")
